const {_electron}=require('playwright-core')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const path=require('node:path')
const {spawn,execFileSync}=require('node:child_process')
const net=require('node:net')
const root=path.resolve(__dirname,'../..')
;(async()=>{
 const listener=net.createServer();await new Promise(resolve=>listener.listen(0,'127.0.0.1',resolve));const port=listener.address().port;await new Promise(resolve=>listener.close(resolve))
 const server='http://127.0.0.1:'+port
 const python=process.env.AGENTBOARD_TEST_PYTHON||'python3'
 const fixture=spawn(python,['-m','uvicorn','backend.tests.desktop_fixture:app','--host','127.0.0.1','--port',String(port),'--log-level','warning'],{cwd:root,stdio:'inherit'})
 let app
 try {
 for(let i=0;i<100;i++){try{if((await fetch(server+'/api/workers')).ok)break}catch{}if(fixture.exitCode!==null)throw Error('Fixture exited');await new Promise(r=>setTimeout(r,100))}
 const profile=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'agentboard-desktop-test-'))
 app=await _electron.launch({executablePath:process.env.AGENTBOARD_ELECTRON_PATH||require('electron'),args:[path.join(root,'desktop'),...(process.getuid?.()===0?['--no-sandbox']:[]),'--user-data-dir='+profile],env:{...process.env,AGENTBOARD_SERVER_URL:''}})
 try{
 let page=await app.firstWindow();page.setDefaultTimeout(12000)
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.getByLabel('서버 주소').fill(server)
 await page.getByRole('button',{name:'연결',exact:true}).click()
 await app.evaluate(async({BrowserWindow},url)=>{await BrowserWindow.getAllWindows()[0].webContents.session.cookies.set({url,name:'token',value:'fixture-token',expirationDate:Date.now()/1000+3600})},server)
 await page.getByTitle('인앱 브라우저 탭 열기').click()
 await page.getByRole('textbox',{name:'웹 주소',exact:true}).fill(server+'/fixture/start')
 await page.getByRole('button',{name:'이동',exact:true}).click()
 const wait=async(fn)=>{for(let i=0;i<100;i++){try{if(await fn())return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('condition timeout')}
 const tabs=()=>page.evaluate(()=>window.agentboardDesktop.invoke({action:'list'}))
 await wait(async()=>(await tabs())[0]?.title==='start')
 assert.equal(await page.locator('.chromium-viewport img').count(),0)
 const tab=(await tabs())[0]
 const command=command=>page.evaluate(async data=>{
  const clients=await (await fetch('/api/desktop/clients')).json()
  const r=await fetch('/api/desktop/clients/'+clients.clients[0].id+'/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})
  if(!r.ok)throw Error(await r.text());return (await r.json()).result
 },command)
 await wait(async()=>await page.locator('.native-browser-status').innerText().then(t=>t.includes('켜짐')))
 console.log('connected',tab.id)
 await command({action:'fill',id:tab.id,selector:'#text',text:'한글 --desktop'})
 let snap=await command({action:'snapshot',id:tab.id});assert.equal(snap.title,'start');assert(snap.elements.some(e=>e.selector==='#text'))
 const nativeValue=()=>app.evaluate(({webContents})=>webContents.getAllWebContents().find(w=>w.getURL().includes('/fixture/start')).executeJavaScript('document.querySelector("#text").value'))
 assert.equal(await nativeValue(),'한글 --desktop')
 await page.locator('.vtab').filter({hasText:'작업 1'}).click()
 await wait(async()=>!(await tabs())[0].visible)
 await page.locator('.vtab').filter({hasText:'start'}).click()
 await wait(async()=>(await tabs())[0].visible)
 assert.equal(await nativeValue(),'한글 --desktop')
 await page.getByTitle('좌우 분할 (선택한 탭을 오른쪽으로)',{exact:true}).click()
 await page.locator('.workbench-split').waitFor()
 await wait(async()=>{
  const r=await page.locator('.native-browser-slot').boundingBox()
  const b=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].contentView.children.find(v=>v.webContents?.getURL().includes('/fixture/start')).getBounds())
  return Math.abs(b.x-r.x)<2&&Math.abs(b.width-r.width)<2
 })
 assert.equal(await nativeValue(),'한글 --desktop')
 await page.reload();await page.locator('.native-browser-slot').waitFor();assert.equal(await nativeValue(),'한글 --desktop')
 await command({action:'click',id:tab.id,selector:'#next'});await wait(async()=>(await tabs())[0].url.endsWith('/next'))
 await page.getByTitle('이전 페이지',{exact:true}).click();await wait(async()=>(await tabs())[0].url.endsWith('/start'))
 const shot=await command({action:'screenshot',id:tab.id});assert.equal(shot.mimeType,'image/png');assert(shot.base64.length>100)
 const isolated=await app.evaluate(({webContents})=>webContents.getAllWebContents().find(w=>w.getURL().includes('/fixture/start')).executeJavaScript('({node:typeof process,bridge:typeof window.agentboardDesktop})'))
 assert.deepEqual(isolated,{node:'undefined',bridge:'undefined'})
 await page.getByRole('checkbox').filter({visible:true}).last().uncheck()
 await wait(async()=>await page.evaluate(async()=>!(await (await fetch('/api/desktop/clients')).json()).clients.length))
 await page.getByRole('checkbox').filter({visible:true}).last().check()
 await wait(async()=>await page.evaluate(async()=>(await (await fetch('/api/desktop/clients')).json()).clients.length===1))
 await page.evaluate(()=>{const overlay=document.createElement('div');overlay.className='spawn-backdrop';overlay.id='fixture-modal';document.body.append(overlay)})
 await wait(async()=>!(await tabs())[0].visible)
 await page.evaluate(()=>document.querySelector('#fixture-modal').remove())
 await wait(async()=>(await tabs())[0].visible)
 await app.evaluate(({webContents})=>webContents.getAllWebContents().find(w=>w.getURL().includes('/fixture/start')).executeJavaScript('localStorage.setItem("workspace-marker","first")'))
 const other='browser:second'
 await command({action:'open',id:other,workspace:'["local","/tmp/agentboard-desktop-fixture/2"]',url:server+'/fixture/other'})
 await wait(async()=>(await tabs()).find(t=>t.id===other)?.title==='other')
 assert.equal((await tabs()).find(t=>t.id===tab.id).visible,false)
 assert.equal(await app.evaluate(({webContents})=>webContents.getAllWebContents().find(w=>w.getURL().includes('/fixture/other')).executeJavaScript('localStorage.getItem("workspace-marker")')),null)
 await app.evaluate(({webContents})=>webContents.getAllWebContents().find(w=>w.getURL().includes('/fixture/other')).executeJavaScript('localStorage.setItem("workspace-marker","second")'))
 await command({action:'close',id:tab.id});await wait(async()=>(await tabs()).length===1)
 await app.close()
 app=await _electron.launch({executablePath:process.env.AGENTBOARD_ELECTRON_PATH||require('electron'),args:[path.join(root,'desktop'),...(process.getuid?.()===0?['--no-sandbox']:[]),'--user-data-dir='+profile],env:{...process.env,AGENTBOARD_SERVER_URL:''}})
 page=await app.firstWindow();page.setDefaultTimeout(12000)
 await wait(async()=>(await tabs()).find(t=>t.id===other)?.title==='other')
 assert.equal(await app.evaluate(({webContents})=>webContents.getAllWebContents().find(w=>w.getURL().includes('/fixture/other')).executeJavaScript('localStorage.getItem("workspace-marker")')),'second')
 await wait(async()=>await page.locator('.native-browser-status').innerText().then(t=>t.includes('켜짐')))
 const cli=JSON.parse(execFileSync(python,['-m','backend.desktop_cli','snapshot','--server',server,'--id',other],{cwd:root,env:{...process.env,AGENTBOARD_AUTH_TOKEN:'fixture-token'}}).toString())
 assert.equal(cli.title,'other')
 assert.equal((await fetch(server+'/api/desktop/clients')).status,401)
 // Electron handles beforeunload itself; do not let Playwright auto-dismiss it.
 page.on('dialog',()=>{})
 await page.evaluate(()=>{window.onbeforeunload=()=>true})
 await app.evaluate(({app,dialog})=>{dialog.showMessageBoxSync=()=>0;setTimeout(()=>app.quit(),0)})
 await new Promise(resolve=>setTimeout(resolve,250))
 assert.equal((await tabs()).length,1,'cancelled app quit must retain web tabs')
 await page.evaluate(()=>{window.onbeforeunload=null})
 await command({action:'close',id:other});await wait(async()=>!(await tabs()).length)
 await wait(async()=>await page.locator('.native-browser-slot').count()===0)
 assert.deepEqual(errors,[])
 console.log('PASS Electron native rendering, agent relay fill/click/snapshot/screenshot, split/refresh/tab state, modal occlusion, workspace isolation, full app restart, relay disable, close')
 }finally{await app.close();app=null}
 }finally{if(app)await app.close();fixture.kill();await new Promise(resolve=>fixture.exitCode!==null?resolve():fixture.once('exit',resolve))}
})().catch(e=>{console.error(e);process.exit(1)})
