import { beforeEach, describe, expect, it } from 'vitest'
import { useStore, viewerKey, workspaceEntries, workspaceId, completionKey, type ViewerTab } from './store'

const tab: ViewerTab = { id: '/project/a.py', path: '/project/a.py', name: 'a.py', type: 'code', lang: 'python', content: 'original', version: 'v1' }
beforeEach(() => {
  localStorage.clear()
  useStore.setState({ sessions: {}, activeId: null, workspaceCwd: '/project', workspaceHost: 'local', _viewerState: {}, _completedAt: {}, workspaceFolders: [], workspaceOrder: [], hiddenWorkspaces: [], unreadCompletions: [] })
})
describe('workspace files', () => {
  it('opens and edits without an agent session', () => {
    useStore.getState().openTab(tab)
    useStore.getState().updateTab(tab.id, 'edited')
    expect(useStore.getState()._viewerState[viewerKey(useStore.getState())].tabs[0]).toMatchObject({ content: 'edited', dirty: true })
  })
  it('shares tabs between sessions but isolates machines and folders', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'bash' })
    s.upsertSession({ id: '2', cwd: '/project', cmd: 'codex' })
    s.upsertSession({ id: 'remote:1', cwd: '/project', cmd: 'bash', host: 'remote' })
    s.setActive('1'); s.openTab(tab)
    const localKey = viewerKey(useStore.getState())
    s.setActive('2')
    expect(viewerKey(useStore.getState())).toBe(localKey)
    s.setActive('remote:1')
    expect(viewerKey(useStore.getState())).not.toBe(localKey)
    s.setWorkspace('/another')
    expect(useStore.getState()._viewerState[viewerKey(useStore.getState())]).toBeUndefined()
  })
  it('finishes an asynchronous save in its original workspace and preserves later edits', () => {
    const s = useStore.getState()
    s.openTab(tab); s.updateTab(tab.id, 'sent to server')
    const key = viewerKey(useStore.getState())
    s.updateTab(tab.id, 'newer typing')
    s.setWorkspace('/other'); s.openTab(tab)
    s.markTabSaved(tab.id, 'sent to server', 'v2', key)
    expect(useStore.getState()._viewerState[key].tabs[0]).toMatchObject({ content: 'newer typing', dirty: true, version: 'v2' })
    expect(useStore.getState()._viewerState[viewerKey(useStore.getState())].tabs[0].version).toBe('v1')
  })
  it('does not resurrect legacy session tabs after the last workspace tab is closed', async () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'bash' })
    localStorage.setItem('agentboard.viewer.1', JSON.stringify({ tabs: [tab] }))
    s.openTab(tab)
    s.closeTab(tab.id)
    const key = viewerKey(useStore.getState())
    useStore.setState({ _viewerState: {} })
    await s.restoreViewerTabs(key)
    expect(useStore.getState()._viewerState[key]).toBeUndefined()
  })
  it('does not flash completed over a new working state', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    expect(s.effectiveState('1')).toBe('working')
  })
})

describe('workspace navigation', () => {
  it('keeps user order when sessions update, including identical paths on different hosts', () => {
    const s = useStore.getState()
    s.addWorkspaceFolder('/alpha'); s.addWorkspaceFolder('/beta')
    s.upsertSession({ id: 'remote:1', cwd: '/alpha', cmd: 'bash', host: 'remote' })
    s.reorderWorkspace(workspaceId('/beta'), workspaceId('/alpha'))
    s.upsertSession({ id: '1', cwd: '/alpha', cmd: 'codex' })
    expect(workspaceEntries(useStore.getState()).map(e => e.key)).toEqual([
      workspaceId('/beta'), workspaceId('/alpha'), workspaceId('/alpha', 'remote'),
    ])
    expect(JSON.parse(localStorage.getItem('agentboard.workspaceOrder')!)[0]).toBe(workspaceId('/beta'))
  })
  it('removes a workspace with live sessions without removing the sessions or drafts', () => {
    const s = useStore.getState()
    s.addWorkspaceFolder('/another')
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' }); s.setActive('1')
    s.openTab(tab); s.updateTab(tab.id, 'unsaved')
    s.removeWorkspaceFolder('/project')
    expect(workspaceEntries(useStore.getState()).map(e => e.cwd)).toEqual(['/another'])
    expect(useStore.getState().sessions['1'].status).toBe('running')
    expect(useStore.getState()._viewerState[workspaceId('/project')].tabs[0].content).toBe('unsaved')
    expect(useStore.getState().workspaceCwd).toBe('/another')
    expect(useStore.getState().activeId).toBeNull()
    s.upsertSession({ id: '2', cwd: '/project', cmd: 'bash' })
    expect(workspaceEntries(useStore.getState()).map(e => e.cwd)).toEqual(['/another'])
    s.restoreWorkspace(workspaceId('/project'))
    expect(workspaceEntries(useStore.getState()).find(e => e.cwd === '/project')?.ids).toEqual(['1','2'])
  })
  it('can restore an empty remote workspace after its session is gone', () => {
    const s = useStore.getState()
    s.upsertSession({ id: 'remote:1', cwd: '/project', cmd: 'bash', host: 'remote' })
    s.removeWorkspaceFolder('/project', 'remote')
    s.removeSession('remote:1')
    s.restoreWorkspace(workspaceId('/project', 'remote'))
    expect(workspaceEntries(useStore.getState())).toMatchObject([{ cwd: '/project', host: 'remote', ids: [] }])
  })
  it('clears selection when removing the last workspace and can reopen its session', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' }); s.setActive('1')
    s.removeWorkspaceFolder('/project')
    expect(useStore.getState().workspaceCwd).toBeNull()
    expect(workspaceEntries(useStore.getState())).toHaveLength(0)
    s.setActive('1')
    expect(workspaceEntries(useStore.getState())).toHaveLength(1)
    expect(useStore.getState().hiddenWorkspaces).toEqual([])
  })
})

describe('unreviewed completions', () => {
  it('keeps a completion until explicitly acknowledged, including the active session', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' }); s.setActive('1')
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    const key = completionKey(useStore.getState().sessions['1'])
    expect(useStore.getState().unreadCompletions).toContain(key)
    expect(JSON.parse(localStorage.getItem('agentboard.unreadCompletions')!)).toContain(key)
    s.setActive('1') // automatic selection is not acknowledgement
    expect(useStore.getState().unreadCompletions).toContain(key)
    s.acknowledgeCompletion('1')
    expect(useStore.getState().unreadCompletions).toEqual([])
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    expect(useStore.getState().unreadCompletions).toEqual([])
  })
  it('keeps new activity visible alongside the unread result and marks process completion', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    expect(s.effectiveState('1')).toBe('working')
    expect(useStore.getState().unreadCompletions).toHaveLength(1)
    s.acknowledgeCompletion('1')
    s.handleMessage({ type: 'status', id: '1', status: 'completed' })
    expect(useStore.getState().unreadCompletions).toHaveLength(1)
    s.removeSession('1')
    expect(useStore.getState().unreadCompletions).toEqual([])
  })
})
