import { beforeEach, describe, expect, it, vi } from 'vitest'
import { api } from './api'
import { useStore, viewerKey, workspaceEntries, workspaceId, completionKey, sessionLabel, type ViewerTab } from './store'

const tab: ViewerTab = { id: '/project/a.py', path: '/project/a.py', name: 'a.py', type: 'code', lang: 'python', content: 'original', version: 'v1' }
beforeEach(() => {
  localStorage.clear()
  useStore.setState({ sessions: {}, activeId: null, workspaceCwd: '/project', workspaceHost: 'local', _viewerState: {}, _restoredWorkspaces: {}, _completedAt: {}, workspaceFolders: [], workspaceOrder: [], hiddenWorkspaces: [], unreadCompletions: [] })
})
describe('workspace files', () => {
  it('opens and edits without an agent session', () => {
    useStore.getState().openTab(tab)
    useStore.getState().updateTab(tab.id, 'edited')
    expect(useStore.getState()._viewerState[viewerKey(useStore.getState())].tabs[0]).toMatchObject({ content: 'edited', dirty: true })
  })
  it('shares tabs between sessions but isolates machines and folders', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'bash' })
    s.upsertSession({ id: '2', cwd: '/project', cmd: 'codex' })
    s.upsertSession({ id: 'remote:1', cwd: '/project', cmd: 'bash', host: 'remote' })
    s.setActive('1'); s.openTab(tab)
    const localKey = viewerKey(useStore.getState())
    s.setActive('2')
    expect(viewerKey(useStore.getState())).toBe(localKey)
    s.setActive('remote:1')
    expect(viewerKey(useStore.getState())).not.toBe(localKey)
    s.setWorkspace('/another')
    expect(useStore.getState()._viewerState[viewerKey(useStore.getState())]).toBeUndefined()
  })
  it('finishes an asynchronous save in its original workspace and preserves later edits', () => {
    const s = useStore.getState()
    s.openTab(tab); s.updateTab(tab.id, 'sent to server')
    const key = viewerKey(useStore.getState())
    s.updateTab(tab.id, 'newer typing')
    s.setWorkspace('/other'); s.openTab(tab)
    s.markTabSaved(tab.id, 'sent to server', 'v2', key)
    expect(useStore.getState()._viewerState[key].tabs[0]).toMatchObject({ content: 'newer typing', dirty: true, version: 'v2' })
    expect(useStore.getState()._viewerState[viewerKey(useStore.getState())].tabs[0].version).toBe('v1')
  })
  it('does not resurrect legacy session tabs after the last workspace tab is closed', async () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'bash' })
    localStorage.setItem('agentboard.viewer.1', JSON.stringify({ tabs: [tab] }))
    s.openTab(tab)
    s.closeTab(tab.id)
    const key = viewerKey(useStore.getState())
    useStore.setState({ _viewerState: {} })
    await s.restoreViewerTabs(key)
    expect(useStore.getState()._viewerState[key]?.tabs || []).toEqual([])
  })
  it('does not flash completed over a new working state', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    expect(s.effectiveState('1')).toBe('working')
  })
})

describe('workspace navigation', () => {
  it('keeps user order when sessions update, including identical paths on different hosts', () => {
    const s = useStore.getState()
    s.addWorkspaceFolder('/alpha'); s.addWorkspaceFolder('/beta')
    s.upsertSession({ id: 'remote:1', cwd: '/alpha', cmd: 'bash', host: 'remote' })
    s.reorderWorkspace(workspaceId('/beta'), workspaceId('/alpha'))
    s.upsertSession({ id: '1', cwd: '/alpha', cmd: 'codex' })
    expect(workspaceEntries(useStore.getState()).map(e => e.key)).toEqual([
      workspaceId('/beta'), workspaceId('/alpha'), workspaceId('/alpha', 'remote'),
    ])
    expect(JSON.parse(localStorage.getItem('agentboard.workspaceOrder')!)[0]).toBe(workspaceId('/beta'))
  })
  it('removes a workspace with live sessions without removing the sessions or drafts', () => {
    const s = useStore.getState()
    s.addWorkspaceFolder('/another')
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' }); s.setActive('1')
    s.openTab(tab); s.updateTab(tab.id, 'unsaved')
    s.removeWorkspaceFolder('/project')
    expect(workspaceEntries(useStore.getState()).map(e => e.cwd)).toEqual(['/another'])
    expect(useStore.getState().sessions['1'].status).toBe('running')
    expect(useStore.getState()._viewerState[workspaceId('/project')].tabs.find(t => t.id === tab.id)?.content).toBe('unsaved')
    expect(useStore.getState().workspaceCwd).toBe('/another')
    expect(useStore.getState().activeId).toBeNull()
    s.upsertSession({ id: '2', cwd: '/project', cmd: 'bash' })
    expect(workspaceEntries(useStore.getState()).map(e => e.cwd)).toEqual(['/another'])
    s.restoreWorkspace(workspaceId('/project'))
    expect(workspaceEntries(useStore.getState()).find(e => e.cwd === '/project')?.ids).toEqual(['1','2'])
  })
  it('can restore an empty remote workspace after its session is gone', () => {
    const s = useStore.getState()
    s.upsertSession({ id: 'remote:1', cwd: '/project', cmd: 'bash', host: 'remote' })
    s.removeWorkspaceFolder('/project', 'remote')
    s.removeSession('remote:1')
    s.restoreWorkspace(workspaceId('/project', 'remote'))
    expect(workspaceEntries(useStore.getState())).toMatchObject([{ cwd: '/project', host: 'remote', ids: [] }])
  })
  it('clears selection when removing the last workspace and can reopen its session', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' }); s.setActive('1')
    s.removeWorkspaceFolder('/project')
    expect(useStore.getState().workspaceCwd).toBeNull()
    expect(workspaceEntries(useStore.getState())).toHaveLength(0)
    s.setActive('1')
    expect(workspaceEntries(useStore.getState())).toHaveLength(1)
    expect(useStore.getState().hiddenWorkspaces).toEqual([])
  })
})

describe('unreviewed completions', () => {
  it('keeps a completion until explicitly acknowledged, including the active session', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' }); s.setActive('1')
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    const key = completionKey(useStore.getState().sessions['1'])
    expect(useStore.getState().unreadCompletions).toContain(key)
    expect(JSON.parse(localStorage.getItem('agentboard.unreadCompletions')!)).toContain(key)
    s.setActive('1') // automatic selection is not acknowledgement
    expect(useStore.getState().unreadCompletions).toContain(key)
    s.acknowledgeCompletion('1')
    expect(useStore.getState().unreadCompletions).toEqual([])
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    expect(useStore.getState().unreadCompletions).toEqual([])
  })
  it('keeps new activity visible alongside the unread result and marks process completion', () => {
    const s = useStore.getState()
    s.upsertSession({ id: '1', cwd: '/project', cmd: 'codex' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'idle' })
    s.handleMessage({ type: 'aiState', id: '1', state: 'working' })
    expect(s.effectiveState('1')).toBe('working')
    expect(useStore.getState().unreadCompletions).toHaveLength(1)
    s.acknowledgeCompletion('1')
    s.handleMessage({ type: 'status', id: '1', status: 'completed' })
    expect(useStore.getState().unreadCompletions).toHaveLength(1)
    s.removeSession('1')
    expect(useStore.getState().unreadCompletions).toEqual([])
  })
})


describe('workbench persistence', () => {
  it('restores reordered file and terminal tabs, active file and reading position', async () => {
    const s = useStore.getState()
    s.upsertSession({id: '1', cwd: '/project', cmd: 'codex'})
    s.setActive('1'); s.openTab(tab)
    const key = viewerKey(useStore.getState())
    s.updateTabView(tab.id, {editorScroll: 780, cursor: 6})
    s.reorderTab(tab.id, 'terminal:1')
    vi.spyOn(api, 'readFile').mockResolvedValue({content: 'fresh content', version: 'v2'} as any)
    useStore.setState({_viewerState: {}, _restoredWorkspaces: {}})
    await s.restoreViewerTabs(key)
    const restored = useStore.getState()._viewerState[key]
    expect(restored.tabs.map(t => t.id)).toEqual([tab.id, 'terminal:1'])
    expect(restored.activeTabId).toBe(tab.id)
    expect(restored.tabs[0]).toMatchObject({content: 'fresh content', viewState: {editorScroll: 780, cursor: 6}})
    s.closeTab('terminal:1')
    expect(useStore.getState().sessions['1']).toBeDefined()
    vi.restoreAllMocks()
  })
  it('keeps PDF position isolated between workspaces and accepts drops after a target', () => {
    const s = useStore.getState(); s.openTab({...tab, type: 'pdf'})
    const key = viewerKey(useStore.getState())
    s.setWorkspace('/other'); s.openTab(tab)
    s.updateTabView(tab.id, {page: 12, zoom: 1.5}, key)
    expect(useStore.getState()._viewerState[key].tabs[0].viewState).toEqual({page:12, zoom:1.5})
    expect(useStore.getState()._viewerState[viewerKey(useStore.getState())].tabs[0].viewState).toBeUndefined()
    s.addWorkspaceFolder('/alpha'); s.addWorkspaceFolder('/beta')
    s.reorderWorkspace(workspaceId('/alpha'), workspaceId('/beta'), true)
    expect(workspaceEntries(useStore.getState()).map(e => e.cwd)).toEqual(['/beta','/alpha'])
  })
})

it('remembers file position after closing and reopening the tab', () => {
  const s = useStore.getState()
  s.openTab(tab); s.updateTabView(tab.id, {editorScroll: 900, cursor: 4}); s.closeTab(tab.id)
  s.openTab(tab)
  expect(useStore.getState()._viewerState[viewerKey(useStore.getState())].tabs[0].viewState).toEqual({editorScroll:900, cursor:4})
})

it('uses agent titles instead of legacy numbered command labels', () => {
  const s = useStore.getState(); s.upsertSession({id:'1', cwd:'/project', cmd:'claude'})
  const session = {...useStore.getState().sessions['1'], autoTitle:'문서 구조 개선'}
  expect(sessionLabel(session, {'1':'claude #1'})).toBe('문서 구조 개선')
  expect(sessionLabel(session, {'1':'내가 지정한 제목'})).toBe('내가 지정한 제목')
  expect(sessionLabel({...session, autoTitle:''}, {})).toBe('claude · 제목 대기')
})

it('prepares every workspace session as a separate tab without replacing the active file', () => {
  const s=useStore.getState()
  s.upsertSession({id:'1',cwd:'/project',cmd:'claude'})
  s.upsertSession({id:'2',cwd:'/project',cmd:'codex'})
  s.upsertSession({id:'3',cwd:'/other',cmd:'codex'})
  s.openTab(tab)
  const key=viewerKey(useStore.getState())
  s.ensureSessionTabs(key);s.ensureSessionTabs(key)
  expect(useStore.getState()._viewerState[key].tabs.map(t=>t.id)).toEqual([tab.id,'terminal:1','terminal:2'])
  expect(useStore.getState()._viewerState[key].activeTabId).toBe(tab.id)
})

it('does not recreate acknowledged completion for the same server result', () => {
  const s=useStore.getState();s.upsertSession({id:'1',cwd:'/project',cmd:'codex'})
  s.handleMessage({type:'aiState',id:'1',state:'working',completionId:''})
  s.handleMessage({type:'aiState',id:'1',state:'idle',completionId:'result-a'})
  expect(useStore.getState().unreadCompletions).toHaveLength(1)
  s.acknowledgeCompletion('1')
  s.handleMessage({type:'aiState',id:'1',state:'working',completionId:'result-a'})
  s.handleMessage({type:'aiState',id:'1',state:'idle',completionId:'result-a'})
  expect(useStore.getState().unreadCompletions).toHaveLength(0)
  s.handleMessage({type:'aiState',id:'1',state:'working',completionId:'result-a'})
  s.handleMessage({type:'aiState',id:'1',state:'idle',completionId:'result-b'})
  expect(useStore.getState().unreadCompletions).toHaveLength(1)
})

it('keeps the live idle state separate from a completed-turn notification', () => {
  const s=useStore.getState();s.upsertSession({id:'1',cwd:'/project',cmd:'codex'})
  s.handleMessage({type:'aiState',id:'1',state:'working',completionId:''})
  s.handleMessage({type:'aiState',id:'1',state:'idle',completionId:'done'})
  expect(s.effectiveState('1')).toBe('idle')
  expect(useStore.getState().unreadCompletions).toHaveLength(1)
  s.acknowledgeCompletion('1')
  expect(s.effectiveState('1')).toBe('idle')
})

it('keeps browser navigation and tabs isolated from files and other workspaces', async () => {
  const s=useStore.getState(), key=viewerKey(useStore.getState())
  s.openBrowser('example.com');s.openBrowser('https://example.com/')
  const view=useStore.getState()._viewerState[key], id=view.tabs[0].id
  expect(view.tabs).toHaveLength(1)
  s.navigateBrowser(id,'https://example.org/next',key)
  s.stepBrowser(id,-1,key)
  expect(useStore.getState()._viewerState[key].tabs[0].browser?.index).toBe(0)
  s.setWorkspace('/another');s.openBrowser('example.com')
  s.stepBrowser(id,1,key)
  expect(useStore.getState()._viewerState[key].tabs[0].browser?.index).toBe(1)
  const read=vi.spyOn(api,'readFile')
  useStore.setState({_viewerState:{},_restoredWorkspaces:{}})
  await s.restoreViewerTabs(key)
  expect(read).not.toHaveBeenCalled()
  expect(useStore.getState()._viewerState[key].tabs[0]).toMatchObject({id,type:'browser',browser:{history:['https://example.com/','https://example.org/next'],index:1}})
  vi.restoreAllMocks()
})
it('never opens a browser tab for executable URLs',()=>{
  const s=useStore.getState();s.openBrowser('javascript:alert(1)')
  expect(useStore.getState()._viewerState[viewerKey(useStore.getState())]).toBeUndefined()
})
